print("gitee test2 , 你在编辑器上看到这里时，你的拉取测试成功了")
print("i will learn how to use git by pycharm")
print("i will learn how to use git by pycharm02")
print("conflict test")
print("i will learn how to use git by pycharm03")
print("test,just test")
print("where there is a well ? there is a way")
print("push test")
print("push by ssh")
print("pull test ,if you can see this sentence , that's provie your pull test success")
print("gitee test ,当你在码云上看到这段话的时候，说明你的测试完成了")